name: platform_detector
description: A lightweight platform detection package for Flutter and Dart that works seamlessly across web, mobile, and desktop without import errors.
version: 0.0.1
homepage: https://github.com/Mohiuddin655-PUB/platform_detector
repository: https://github.com/Mohiuddin655-PUB/platform_detector
issue_tracker: https://github.com/Mohiuddin655-PUB/platform_detector/issues
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  platform_detector:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true